import { useState } from 'react'
import Head from 'next/head'
import Link from 'next/link'
import Header from '../components/header/Header'
import Author from '../components/author/Author'
import Advert from '../components/advert/Advert'
import Footer from '../components/footer/Footer'
import { Row, Col, List} from 'antd'
import { CalendarOutlined, FolderOpenOutlined, FireOutlined } from '@ant-design/icons'
import axios from 'axios'
// css
import styles from '../styles/Home.module.css'
// url
import serivePath from '../config/baseUrl'

// SEO优化
export default function Home(list) {
  const [ mylist, setMylist ] = useState(list.data)
  return (
    <div className={styles.container}>
      <Head>
        <title>HEISMING-index</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Row className="comm-main" type="flex" justify="center">
        {/* 主页left */}
        <Col className="comm-left" xs={24} sm={24} md={16} lg={18} xl={14}>
         <List 
           header={<div>最新日志</div>}
           itemLayout="vertical"
           dataSource={mylist}
           renderItem={item => {
             return (
               <List.Item>
                 {/* 点击跳转 */}
                 <Link href={{pathname: '/details', query: { id: item.id }}}>
                    <a>
                      <div className="list-title">{item.title}</div>
                    </a>
                 </Link>
                 <div className="list-icon">
                    <span><CalendarOutlined />&nbsp;{item.addTime}&nbsp;</span>
                    <span><FolderOpenOutlined />&nbsp;{item.typeName}&nbsp;</span>
                    <span><FireOutlined />&nbsp;{item.view_count}人&nbsp;</span>
                 </div>
                 <div className="list-context">{item.introduce}</div>
               </List.Item>
             )
           }}
         />
        </Col>
        {/* 主页right */}
        <Col className="comm-right" xs={0} sm={0} md={7} lg={5} xl={4}>
         <Author/>
         <Advert/>
        </Col>
      </Row>
      {/* 底部 */}
      <Footer/>
    </div>
  )
}

Home.getInitialProps = async () => {
  const promise = new Promise((resolve, reject) => {
    axios(serivePath.getArticleList).then(
      (res) => {
        console.log('------------------>', res)
        resolve(res.data)
      }
    )
  })
  return await promise
}