import React, { useState, useEffect } from 'react'
import Head from 'next/head'
import Header from '../components/header/Header'
import Author from '../components/author/Author'
import Advert from '../components/advert/Advert'
import Footer from '../components/footer/Footer'
import { Row, Col, List, Breadcrumb } from 'antd'
import { CalendarOutlined, FolderOpenOutlined, FireOutlined } from '@ant-design/icons'
// css
import styles from '../styles/Home.module.css'
// ajax
import axios from 'axios'
// api
import serivePath from '../config/baseUrl'
// link a
import Link from 'next/link'
// markdown
import { marked } from 'marked'
import highlightJS from 'highlight.js'
import 'highlight.js/styles/monokai-sublime.css'

// SEO优化
export default function MyList(list) {
  const [ mylist, setMylist ] = useState(list.data)
  // SPA
  useEffect(() => {
    setMylist(list.data)
  }) 
  // markdown解析
  const renderer = new marked.Renderer();
  marked.setOptions({
    renderer,
    gfm: true,
    // 容错
    pedantic: false,
    // 忽略HTML标签
    sanitize: false,
    // 
    tables: true,
    // 换行符
    breaks: false,
    // 自动渲染列表样式
    smartLists: true,
    smartypants: false,
    highlight: function(code) {
      return highlightJS.highlightAuto(code).value
    }
  })

  return (
    <div className={styles.container}>
      <Head>
        <title>HEISMING-list</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Row className="comm-main" type="flex" justify="center">
        <Col className="comm-left" xs={24} sm={24} md={16} lg={18} xl={14}>
          <div className="bread-div">
            <Breadcrumb>
              <Breadcrumb.Item><a href="/">首页</a></Breadcrumb.Item>
              <Breadcrumb.Item>文章</Breadcrumb.Item>
            </Breadcrumb>
          </div>
         <List 
           header={<div>最新日志</div>}
           itemLayout="vertical"
           dataSource={mylist}
           renderItem={item => {
             return (
               <List.Item>
                  <div className="list-title">
                    <Link href={{ pathname: '/details', query: { id: item.id }}}>
                      <a>
                        {item.title}
                      </a>
                    </Link>
                  </div>
                  <div className="list-icon">
                      <span><CalendarOutlined />&nbsp;{item.addTime}&nbsp;</span>
                      <span><FolderOpenOutlined />&nbsp;{item.typeName}&nbsp;</span>
                      <span><FireOutlined />&nbsp;{item.view_count}人&nbsp;</span>
                  </div>
                  <div className="list-context"
                    dangerouslySetInnerHTML={{__html: marked(item.introduce)}}
                  >
                  </div>
               </List.Item>
             )
           }}
         />
        </Col>
        <Col className="comm-right" xs={0} sm={0} md={7} lg={5} xl={4}>
         <Author/>
         <Advert/>
        </Col>
      </Row>
      {/* 底部信息 */}
      <Footer/>
    </div>
  )
}

MyList.getInitialProps = async (context) => {
  const id = context.query.id
  return await new Promise((resolve, reject) => {
    axios(serivePath.getArticleListById + id).then(
      res => resolve(res.data)
    )
  })
}